name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Wasm
        run: wasm-pack build
        working-directory: ${{ github.workspace }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install npm dependencies
        run: npm install
        working-directory: www

      - name: Build site
        run: npm run build
        working-directory: www

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan gh-pages
          git --set-upstream-to=origin/main
          git rm -rf .
          cp -r www/dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
